name: "PBRP Build Action"
author: 'Ragebreaker'
description: "A GitHub action to build PitchBlack Recovery Project (PBRP) for a specified device."

inputs:
  MANIFEST_BRANCH:
    description: 'PBRP Manifest Branch'
    default: 'android-9.0'
    type: choice
    options:
      - android-12.1
      - android-11.0
      - android-10.0
      - android-9.0
      - android-8.1
      - android-7.1
      - android-6.0
  DEVICE_TREE:
    description: 'Custom Recovery Tree URL (your device tree repository)'
    default: 'https://github.com/vados-dev/sl8541e_cus_go'
    type: string
   DEVICE_TREE_BRANCH:
    description: 'Custom Recovery Tree Branch (leave blank to use the default branch of the repository)'
    default: 'sl8541e_cus_go'
    type: string
  DEVICE_NAME:
    description: 'Specify your Device Codename (leave blank to auto-detect)'
    default: 'omni_sl8541e_cus_go'
    type: string
  DEVICE_PATH:
    description: 'Specify your Device Path (leave blank to auto-detect)'
    default: 'device/sprd/sl8541e_cus_go'
    type: string
  BUILD_TARGET:
    description: 'Specify your Build Target (use "pbrp" for Android 11 or above)'
    default: 'pbrp'
    type: choice
    options:
      - pbrp
      - boot
      - recovery
      - vendorboot

  outputs:
    out_img:
      description: 'Path to the built recovery image'
    out_zip:
      description: 'Path to the built recovery ZIP file'

runs:
  using: 'composite'
  steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "MANIFEST_BRANCH=${{ inputs.MANIFEST_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_TREE=${{ inputs.DEVICE_TREE }}" >> $GITHUB_ENV
        echo "DEVICE_TREE_BRANCH=${{ inputs.DEVICE_TREE_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_NAME=${{ inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        echo "DEVICE_PATH=${{ inputs.DEVICE_PATH }}" >> $GITHUB_ENV
        echo "BUILD_TARGET=${{ inputs.BUILD_TARGET }}" >> $GITHUB_ENV

    - name: 'Build PBRP'
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh

branding:
  icon: "terminal"
  color: "black"
